/*
 * SCDCPAJUv3
 * # This is a SCDCPAJUv3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SCDCPAJUv3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.scsp.api.cedent.client.SCDCPAJUv3.model.ClaveHojaPadronal;
import es.caib.scsp.api.cedent.client.SCDCPAJUv3.model.Domicilio;
import es.caib.scsp.api.cedent.client.SCDCPAJUv3.model.Personas;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * Resultado
 */


public class Resultado {
  @JsonProperty("claveHojaPadronal")
  private ClaveHojaPadronal claveHojaPadronal = null;

  @JsonProperty("domicilio")
  private Domicilio domicilio = null;

  @JsonProperty("personas")
  private Personas personas = null;

  @JsonProperty("fechaExpedicion")
  private DateTime fechaExpedicion = null;

  public Resultado claveHojaPadronal(ClaveHojaPadronal claveHojaPadronal) {
    this.claveHojaPadronal = claveHojaPadronal;
    return this;
  }

   /**
   * Get claveHojaPadronal
   * @return claveHojaPadronal
  **/
  @Schema(required = true, description = "")
  public ClaveHojaPadronal getClaveHojaPadronal() {
    return claveHojaPadronal;
  }

  public void setClaveHojaPadronal(ClaveHojaPadronal claveHojaPadronal) {
    this.claveHojaPadronal = claveHojaPadronal;
  }

  public Resultado domicilio(Domicilio domicilio) {
    this.domicilio = domicilio;
    return this;
  }

   /**
   * Get domicilio
   * @return domicilio
  **/
  @Schema(required = true, description = "")
  public Domicilio getDomicilio() {
    return domicilio;
  }

  public void setDomicilio(Domicilio domicilio) {
    this.domicilio = domicilio;
  }

  public Resultado personas(Personas personas) {
    this.personas = personas;
    return this;
  }

   /**
   * Get personas
   * @return personas
  **/
  @Schema(required = true, description = "")
  public Personas getPersonas() {
    return personas;
  }

  public void setPersonas(Personas personas) {
    this.personas = personas;
  }

  public Resultado fechaExpedicion(DateTime fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
    return this;
  }

   /**
   * Get fechaExpedicion
   * @return fechaExpedicion
  **/
  @Schema(required = true, description = "")
  public DateTime getFechaExpedicion() {
    return fechaExpedicion;
  }

  public void setFechaExpedicion(DateTime fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resultado resultado = (Resultado) o;
    return Objects.equals(this.claveHojaPadronal, resultado.claveHojaPadronal) &&
        Objects.equals(this.domicilio, resultado.domicilio) &&
        Objects.equals(this.personas, resultado.personas) &&
        Objects.equals(this.fechaExpedicion, resultado.fechaExpedicion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claveHojaPadronal, domicilio, personas, fechaExpedicion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resultado {\n");
    
    sb.append("    claveHojaPadronal: ").append(toIndentedString(claveHojaPadronal)).append("\n");
    sb.append("    domicilio: ").append(toIndentedString(domicilio)).append("\n");
    sb.append("    personas: ").append(toIndentedString(personas)).append("\n");
    sb.append("    fechaExpedicion: ").append(toIndentedString(fechaExpedicion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
