/*
 * SCDHPAJUv3
 * # This is a SCDHPAJUv3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SCDHPAJUv3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.Titular;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Solicitud
 */


public class Solicitud {
  @JsonProperty("provinciaSolicitud")
  private String provinciaSolicitud = null;

  @JsonProperty("municipioSolicitud")
  private String municipioSolicitud = null;

  @JsonProperty("titular")
  private Titular titular = null;

  @JsonProperty("numeroAnyos")
  private String numeroAnyos = null;

  public Solicitud provinciaSolicitud(String provinciaSolicitud) {
    this.provinciaSolicitud = provinciaSolicitud;
    return this;
  }

   /**
   * Get provinciaSolicitud
   * @return provinciaSolicitud
  **/
  @Schema(required = true, description = "")
  public String getProvinciaSolicitud() {
    return provinciaSolicitud;
  }

  public void setProvinciaSolicitud(String provinciaSolicitud) {
    this.provinciaSolicitud = provinciaSolicitud;
  }

  public Solicitud municipioSolicitud(String municipioSolicitud) {
    this.municipioSolicitud = municipioSolicitud;
    return this;
  }

   /**
   * Get municipioSolicitud
   * @return municipioSolicitud
  **/
  @Schema(required = true, description = "")
  public String getMunicipioSolicitud() {
    return municipioSolicitud;
  }

  public void setMunicipioSolicitud(String municipioSolicitud) {
    this.municipioSolicitud = municipioSolicitud;
  }

  public Solicitud titular(Titular titular) {
    this.titular = titular;
    return this;
  }

   /**
   * Get titular
   * @return titular
  **/
  @Schema(required = true, description = "")
  public Titular getTitular() {
    return titular;
  }

  public void setTitular(Titular titular) {
    this.titular = titular;
  }

  public Solicitud numeroAnyos(String numeroAnyos) {
    this.numeroAnyos = numeroAnyos;
    return this;
  }

   /**
   * Get numeroAnyos
   * @return numeroAnyos
  **/
  @Schema(description = "")
  public String getNumeroAnyos() {
    return numeroAnyos;
  }

  public void setNumeroAnyos(String numeroAnyos) {
    this.numeroAnyos = numeroAnyos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Solicitud solicitud = (Solicitud) o;
    return Objects.equals(this.provinciaSolicitud, solicitud.provinciaSolicitud) &&
        Objects.equals(this.municipioSolicitud, solicitud.municipioSolicitud) &&
        Objects.equals(this.titular, solicitud.titular) &&
        Objects.equals(this.numeroAnyos, solicitud.numeroAnyos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provinciaSolicitud, municipioSolicitud, titular, numeroAnyos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Solicitud {\n");
    
    sb.append("    provinciaSolicitud: ").append(toIndentedString(provinciaSolicitud)).append("\n");
    sb.append("    municipioSolicitud: ").append(toIndentedString(municipioSolicitud)).append("\n");
    sb.append("    titular: ").append(toIndentedString(titular)).append("\n");
    sb.append("    numeroAnyos: ").append(toIndentedString(numeroAnyos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
