/*
 * SVDSCTFNWS01v3
 * # This is a SVDSCTFNWS01v3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model.DatosPersonales;
import es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model.Documentacion;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DatosAdicionalesTitular
 */


public class DatosAdicionalesTitular {
  @JsonProperty("documentacion")
  private Documentacion documentacion = null;

  @JsonProperty("datosPersonales")
  private DatosPersonales datosPersonales = null;

  public DatosAdicionalesTitular documentacion(Documentacion documentacion) {
    this.documentacion = documentacion;
    return this;
  }

   /**
   * Get documentacion
   * @return documentacion
  **/
  @Schema(description = "")
  public Documentacion getDocumentacion() {
    return documentacion;
  }

  public void setDocumentacion(Documentacion documentacion) {
    this.documentacion = documentacion;
  }

  public DatosAdicionalesTitular datosPersonales(DatosPersonales datosPersonales) {
    this.datosPersonales = datosPersonales;
    return this;
  }

   /**
   * Get datosPersonales
   * @return datosPersonales
  **/
  @Schema(description = "")
  public DatosPersonales getDatosPersonales() {
    return datosPersonales;
  }

  public void setDatosPersonales(DatosPersonales datosPersonales) {
    this.datosPersonales = datosPersonales;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatosAdicionalesTitular datosAdicionalesTitular = (DatosAdicionalesTitular) o;
    return Objects.equals(this.documentacion, datosAdicionalesTitular.documentacion) &&
        Objects.equals(this.datosPersonales, datosAdicionalesTitular.datosPersonales);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentacion, datosPersonales);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatosAdicionalesTitular {\n");
    
    sb.append("    documentacion: ").append(toIndentedString(documentacion)).append("\n");
    sb.append("    datosPersonales: ").append(toIndentedString(datosPersonales)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
