/*
 * SVDSCTFNWS01v3
 * # This is a SVDSCTFNWS01v3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model.DatosAdicionalesTitular;
import es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model.TituloFamiliaNumerosa;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Solicitud
 */


public class Solicitud {
  @JsonProperty("tituloFamiliaNumerosa")
  private TituloFamiliaNumerosa tituloFamiliaNumerosa = null;

  @JsonProperty("titular")
  private DatosAdicionalesTitular titular = null;

  public Solicitud tituloFamiliaNumerosa(TituloFamiliaNumerosa tituloFamiliaNumerosa) {
    this.tituloFamiliaNumerosa = tituloFamiliaNumerosa;
    return this;
  }

   /**
   * Get tituloFamiliaNumerosa
   * @return tituloFamiliaNumerosa
  **/
  @Schema(required = true, description = "")
  public TituloFamiliaNumerosa getTituloFamiliaNumerosa() {
    return tituloFamiliaNumerosa;
  }

  public void setTituloFamiliaNumerosa(TituloFamiliaNumerosa tituloFamiliaNumerosa) {
    this.tituloFamiliaNumerosa = tituloFamiliaNumerosa;
  }

  public Solicitud titular(DatosAdicionalesTitular titular) {
    this.titular = titular;
    return this;
  }

   /**
   * Get titular
   * @return titular
  **/
  @Schema(required = true, description = "")
  public DatosAdicionalesTitular getTitular() {
    return titular;
  }

  public void setTitular(DatosAdicionalesTitular titular) {
    this.titular = titular;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Solicitud solicitud = (Solicitud) o;
    return Objects.equals(this.tituloFamiliaNumerosa, solicitud.tituloFamiliaNumerosa) &&
        Objects.equals(this.titular, solicitud.titular);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tituloFamiliaNumerosa, titular);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Solicitud {\n");
    
    sb.append("    tituloFamiliaNumerosa: ").append(toIndentedString(tituloFamiliaNumerosa)).append("\n");
    sb.append("    titular: ").append(toIndentedString(titular)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
