/*
 * SVDSCTFNWS01v3
 * # This is a SVDSCTFNWS01v3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TituloFamiliaNumerosa
 */


public class TituloFamiliaNumerosa {
  @JsonProperty("codigoComunidadAutonoma")
  private String codigoComunidadAutonoma = null;

  @JsonProperty("numeroTitulo")
  private String numeroTitulo = null;

  @JsonProperty("fechaConsulta")
  private String fechaConsulta = null;

  public TituloFamiliaNumerosa codigoComunidadAutonoma(String codigoComunidadAutonoma) {
    this.codigoComunidadAutonoma = codigoComunidadAutonoma;
    return this;
  }

   /**
   * Get codigoComunidadAutonoma
   * @return codigoComunidadAutonoma
  **/
  @Schema(required = true, description = "")
  public String getCodigoComunidadAutonoma() {
    return codigoComunidadAutonoma;
  }

  public void setCodigoComunidadAutonoma(String codigoComunidadAutonoma) {
    this.codigoComunidadAutonoma = codigoComunidadAutonoma;
  }

  public TituloFamiliaNumerosa numeroTitulo(String numeroTitulo) {
    this.numeroTitulo = numeroTitulo;
    return this;
  }

   /**
   * Get numeroTitulo
   * @return numeroTitulo
  **/
  @Schema(description = "")
  public String getNumeroTitulo() {
    return numeroTitulo;
  }

  public void setNumeroTitulo(String numeroTitulo) {
    this.numeroTitulo = numeroTitulo;
  }

  public TituloFamiliaNumerosa fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TituloFamiliaNumerosa tituloFamiliaNumerosa = (TituloFamiliaNumerosa) o;
    return Objects.equals(this.codigoComunidadAutonoma, tituloFamiliaNumerosa.codigoComunidadAutonoma) &&
        Objects.equals(this.numeroTitulo, tituloFamiliaNumerosa.numeroTitulo) &&
        Objects.equals(this.fechaConsulta, tituloFamiliaNumerosa.fechaConsulta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigoComunidadAutonoma, numeroTitulo, fechaConsulta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TituloFamiliaNumerosa {\n");
    
    sb.append("    codigoComunidadAutonoma: ").append(toIndentedString(codigoComunidadAutonoma)).append("\n");
    sb.append("    numeroTitulo: ").append(toIndentedString(numeroTitulo)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
