/*
 * SVDSCTFNWS01v3
 * # This is a SVDSCTFNWS01v3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model.Categoria;
import es.caib.scsp.api.cedent.client.SVDSCTFNWS01v3.model.TituloVigente;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TituloFamiliaNumerosaRetorno
 */


public class TituloFamiliaNumerosaRetorno {
  @JsonProperty("codigoComunidadAutonoma")
  private String codigoComunidadAutonoma = null;

  @JsonProperty("numeroTitulo")
  private String numeroTitulo = null;

  @JsonProperty("categoria")
  private Categoria categoria = null;

  @JsonProperty("tituloVigente")
  private TituloVigente tituloVigente = null;

  @JsonProperty("fechaCaducidad")
  private String fechaCaducidad = null;

  @JsonProperty("numeroHijos")
  private Integer numeroHijos = null;

  public TituloFamiliaNumerosaRetorno codigoComunidadAutonoma(String codigoComunidadAutonoma) {
    this.codigoComunidadAutonoma = codigoComunidadAutonoma;
    return this;
  }

   /**
   * Get codigoComunidadAutonoma
   * @return codigoComunidadAutonoma
  **/
  @Schema(description = "")
  public String getCodigoComunidadAutonoma() {
    return codigoComunidadAutonoma;
  }

  public void setCodigoComunidadAutonoma(String codigoComunidadAutonoma) {
    this.codigoComunidadAutonoma = codigoComunidadAutonoma;
  }

  public TituloFamiliaNumerosaRetorno numeroTitulo(String numeroTitulo) {
    this.numeroTitulo = numeroTitulo;
    return this;
  }

   /**
   * Get numeroTitulo
   * @return numeroTitulo
  **/
  @Schema(description = "")
  public String getNumeroTitulo() {
    return numeroTitulo;
  }

  public void setNumeroTitulo(String numeroTitulo) {
    this.numeroTitulo = numeroTitulo;
  }

  public TituloFamiliaNumerosaRetorno categoria(Categoria categoria) {
    this.categoria = categoria;
    return this;
  }

   /**
   * Get categoria
   * @return categoria
  **/
  @Schema(description = "")
  public Categoria getCategoria() {
    return categoria;
  }

  public void setCategoria(Categoria categoria) {
    this.categoria = categoria;
  }

  public TituloFamiliaNumerosaRetorno tituloVigente(TituloVigente tituloVigente) {
    this.tituloVigente = tituloVigente;
    return this;
  }

   /**
   * Get tituloVigente
   * @return tituloVigente
  **/
  @Schema(description = "")
  public TituloVigente getTituloVigente() {
    return tituloVigente;
  }

  public void setTituloVigente(TituloVigente tituloVigente) {
    this.tituloVigente = tituloVigente;
  }

  public TituloFamiliaNumerosaRetorno fechaCaducidad(String fechaCaducidad) {
    this.fechaCaducidad = fechaCaducidad;
    return this;
  }

   /**
   * Get fechaCaducidad
   * @return fechaCaducidad
  **/
  @Schema(description = "")
  public String getFechaCaducidad() {
    return fechaCaducidad;
  }

  public void setFechaCaducidad(String fechaCaducidad) {
    this.fechaCaducidad = fechaCaducidad;
  }

  public TituloFamiliaNumerosaRetorno numeroHijos(Integer numeroHijos) {
    this.numeroHijos = numeroHijos;
    return this;
  }

   /**
   * Get numeroHijos
   * @return numeroHijos
  **/
  @Schema(description = "")
  public Integer getNumeroHijos() {
    return numeroHijos;
  }

  public void setNumeroHijos(Integer numeroHijos) {
    this.numeroHijos = numeroHijos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TituloFamiliaNumerosaRetorno tituloFamiliaNumerosaRetorno = (TituloFamiliaNumerosaRetorno) o;
    return Objects.equals(this.codigoComunidadAutonoma, tituloFamiliaNumerosaRetorno.codigoComunidadAutonoma) &&
        Objects.equals(this.numeroTitulo, tituloFamiliaNumerosaRetorno.numeroTitulo) &&
        Objects.equals(this.categoria, tituloFamiliaNumerosaRetorno.categoria) &&
        Objects.equals(this.tituloVigente, tituloFamiliaNumerosaRetorno.tituloVigente) &&
        Objects.equals(this.fechaCaducidad, tituloFamiliaNumerosaRetorno.fechaCaducidad) &&
        Objects.equals(this.numeroHijos, tituloFamiliaNumerosaRetorno.numeroHijos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigoComunidadAutonoma, numeroTitulo, categoria, tituloVigente, fechaCaducidad, numeroHijos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TituloFamiliaNumerosaRetorno {\n");
    
    sb.append("    codigoComunidadAutonoma: ").append(toIndentedString(codigoComunidadAutonoma)).append("\n");
    sb.append("    numeroTitulo: ").append(toIndentedString(numeroTitulo)).append("\n");
    sb.append("    categoria: ").append(toIndentedString(categoria)).append("\n");
    sb.append("    tituloVigente: ").append(toIndentedString(tituloVigente)).append("\n");
    sb.append("    fechaCaducidad: ").append(toIndentedString(fechaCaducidad)).append("\n");
    sb.append("    numeroHijos: ").append(toIndentedString(numeroHijos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
