openapi: 3.0.0
info:
  title: SCDCPAJUv3
  # CommonMark syntax allowed here
  description: '# This is a SCDCPAJUv3 server spec

                You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.'
  termsOfService: https://www.caib.es/sites/interoperabilitat/es/plataforma_de_interoperabilidad-55365/
  contact:
    email: pinbal@fundaciobit.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://{username}.{domain}:{port}/{basePath}
    description: The production API server
    variables:
      username:
        # note! no enum here means it is an open value
        default: emiserv
        description: this value is assigned by the service provider, in this example `fundaciobit.org`
      domain:
        default: fundaciobit.org
        description: Description
      port:
        enum:
          - '80'
          - '8080'
          - '8443'
          - '443'
        default: '8080'
      basePath:
        # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
        default: /emiservbackofficeapi/externa/services
paths:
  /SCDCPAJUv3/peticionSincrona:
    post:
      tags:
      - SCDCPAJUv3
      summary: Realitza una consulta al cedent
      description: Realitza una consulta al cedent
      operationId: peticionSincrona
      requestBody:
        description: Dades de la consulta
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Solicitud'
            examples:
              solicitud:
                summary: Exemple de Solicitud
                externalValue: 'http://foo.bar/examples/user-example.json'
        required: true
      responses:
        200:
          description: Petició processada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
        400:
          description: Petició errònia
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

components:

  schemas:

    Solicitud:
      type: object
      required:
        - provinciaSolicitud
        - municipioSolicitud
        - titular
      properties:
        provinciaSolicitud:
          $ref: "#/components/schemas/ProvinciaSolicitud"
        municipioSolicitud:
          $ref: "#/components/schemas/MunicipioSolicitud"
        titular:
          $ref: "#/components/schemas/Titular"
      xml:
        name: Solicitud

    ProvinciaSolicitud:
      type: string
      maxLength: 2
      description: "Codi de la Província a la que es sol·liciten les dades de padró del titular de la consulta. Aquests camps aniran codificats amb les taules de codis de l'INE."
      xml:
        name: ProvinciaSolicitud

    MunicipioSolicitud:
      type: string
      maxLength: 3
      description: "Codi del municipi de la província al que es sol·liciten les dades de padró del titular de la consulta. Aquests camps aniran codificats amb les taules de codis de l'INE."
      xml:
        name: MunicipioSolicitud

    Titular:
      oneOf:
        - documentacion:
          $ref: "#/components/schemas/Documentacion"
        - datosPersonales:
          $ref: "#/components/schemas/DatosPersonales"
      xml:
        name: Titular

    Documentacion:
      type: object
      required:
        - tipo
        - valor
      properties:
        tipo:
          type: string
          description: "Possibles valors son NIF, DNI, NIE, Passaport."
          enum:
            - NIF
            - DNI
            - NIE
            - Passaport
          xml:
            name: Tipo
        valor:
          type: string
          maxLength: 14
          description: "Valor del document del titular sense cap espai en blanc."
          xml:
            name: Valor
        numSoporte:
          type: string
          maxLength: 9
          description: ""
          xml:
            name: NumSoporte
      xml:
        name: Documentacion

    DatosPersonales:
      type: object
      required:
      - nombre
      - apellido1
      properties:
        documentacion:
          $ref: "#/components/schemas/Documentacion"
        nombre:
          $ref: "#/components/schemas/Nombre"
        particula1:
          $ref: "#/components/schemas/Particula1"
        apellido1:
          $ref: "#/components/schemas/Apellido1"
        particula2:
          $ref: "#/components/schemas/Particula2"
        apellido2:
          $ref: "#/components/schemas/Apellido2"
        fechaNacimiento:
          $ref: "#/components/schemas/FechaNacimiento"
      xml:
        name: DatosPersonales

    Nombre:
      type: string
      maxLength: 40
      description: "Nom del titular de la sol·licitud."
      xml:
        name: Nombre

    Particula1:
      type: string
      maxLength: 6
      description: "Partícula prèvia al primer cognom."
      xml:
        name: Particula1

    Apellido1:
      type: string
      maxLength: 40
      description: "Primer cognom del titular de la sol·licitud."
      xml:
        name: Apellido1

    Particula2:
      type: string
      maxLength: 6
      description: "Partícula prèvia al segon cognom."
      xml:
        name: Particula2

    Apellido2:
      type: string
      maxLength: 40
      description: "Segon cognom del titular de la sol·licitud."
      xml:
        name: Apellido2

    FechaNacimiento:
      type: string
      format: date-time
      description: "Data de naixement del titular de la sol·licitud. Format:yyyy-MM-dd"
      xml:
        name: FechaNacimiento

    Resultado:
      type: object
      required:
      - claveHojaPadronal
      - domicilio
      - personas
      - fechaExpedicion
      properties:
        claveHojaPadronal:
          $ref: "#/components/schemas/ClaveHojaPadronal"
        domicilio:
          $ref: "#/components/schemas/Domicilio"
        personas:
          $ref: "#/components/schemas/Personas"
        fechaExpedicion:
          $ref: "#/components/schemas/FechaExpedicion"
      xml:
        name: Resultado

    ClaveHojaPadronal:
      type: object
      required:
        - distrito
        - seccion
        - hoja
      properties:
        distrito:
          type: string
          maxLength: 3
          description: "Dada districte del domicili al padró municipal."
          xml:
            name: Distrito
        seccion:
          type: string
          maxLength: 3
          description: "Dada secció del domicili al padró municipal."
          xml:
            name: Seccion
        hoja:
          type: string
          maxLength: 10
          description: "Dada fulla d'inscripció del domicili al padró municipal."
          xml:
            name: Hoja
      xml:
        name: ClaveHojaPadronal

    Domicilio:
      type: object
      required:
        - via
      properties:
        via:
          $ref: "#/components/schemas/Via"
        numero:
          $ref: "#/components/schemas/Numero"
        numeroSuperior:
          $ref: "#/components/schemas/NumeroSuperior"
        kmt:
          $ref: "#/components/schemas/Kmt"
        hmt:
          $ref: "#/components/schemas/Hmt"
        bloque:
          $ref: "#/components/schemas/Bloque"
        portal:
          $ref: "#/components/schemas/Portal"
        escalera:
          $ref: "#/components/schemas/Escalera"
        planta:
          $ref: "#/components/schemas/Planta"
        puerta:
          $ref: "#/components/schemas/Puerta"
        codPostal:
          $ref: "#/components/schemas/CodPostal"
      xml:
        name: Domicilio

    Personas:
      type: object
      properties:
        domicilio:
          type: array
          xml:
            name: Persona
            wrapped: false
          items:
            $ref: "#/components/schemas/Persona"
      xml:
        name: Personas

    FechaExpedicion:
      type: string
      maxLength: 10
      format: date-time
      description: "Data en la que s'expedeixen les dades sol·licitades. Format:yyyy-MM-dd"
      xml:
        name: FechaExpedicion

    Persona:
      type: object
      required:
      - nombre
      - apellido1
      - NIA
      properties:
        nombre:
          $ref: "#/components/schemas/Nombre"
        particula1:
          $ref: "#/components/schemas/Particula1"
        apellido1:
          $ref: "#/components/schemas/Apellido1"
        particula2:
          $ref: "#/components/schemas/Particula2"
        apellido2:
          $ref: "#/components/schemas/Apellido2"
        fechaNacimiento:
          $ref: "#/components/schemas/FechaNacimiento"
        documentacion:
          $ref: "#/components/schemas/Documentacion"
        nia:
          $ref: "#/components/schemas/NIA"
        periodoInscripcion:
          $ref: "#/components/schemas/PeriodoInscripcion"
      xml:
        name: Persona

    PeriodoInscripcion:
      type: object
      required:
      - desde
      - motivoInscripcion
      properties:
        desde:
          $ref: "#/components/schemas/Desde"
        motivoInscripcion:
          $ref: "#/components/schemas/MotivoInscripcion"
      xml:
        name: PeriodoInscripcion

    Via:
      type: object
      required:
        - tipo
        - nombre
      properties:
        codigo:
          type: string
          maxLength: 5
          description: "Codi de la via."
          xml:
            name: Codigo
        tipo:
          type: string
          maxLength: 5
          description: "Tipus de la via."
          xml:
            name: Tipo
        nombre:
          type: string
          maxLength: 70
          description: "Nom de la via."
          xml:
            name: Nombre
      xml:
        name: Via

    Numero:
      type: object
      properties:
        calificador:
          type: string
          maxLength: 1
          description: "Qualificador número."
          xml:
            name: Calificador
        valor:
          type: string
          maxLength: 4
          description: "Valor número."
          xml:
            name: Valor
      xml:
        name: Numero

    NumeroSuperior:
      type: object
      properties:
        calificador:
          type: string
          maxLength: 1
          description: "Qualificador número superior."
          xml:
            name: Calificador
        valor:
          type: string
          maxLength: 4
          description: "Valor número superior."
          xml:
            name: Valor
      xml:
        name: NumeroSuperior

    Kmt:
      type: string
      maxLength: 3
      description: "Quilòmetre del domicili del titular."
      xml:
        name: Kmt

    Hmt:
      type: string
      maxLength: 1
      description: "Hectòmetre del domicili del titular."
      xml:
        name: Hmt

    Bloque:
      type: string
      maxLength: 2
      description: "Bloc del domicili del titular."
      xml:
        name: Bloque

    Portal:
      type: string
      maxLength: 2
      description: "Portal del domicili del titular."
      xml:
        name: Portal

    Escalera:
      type: string
      maxLength: 2
      description: "Escala del domicili del titular."
      xml:
        name: Portal

    Planta:
      type: string
      maxLength: 3
      description: "Planta del domicili del titular."
      xml:
        name: Planta
    
    Puerta:
      type: string
      maxLength: 4
      description: "Porta del domicili del titular."
      xml:
        name: Puerta
    
    CodPostal:
      type: string
      maxLength: 5
      description: "Codi postal del domicili del titular."
      xml:
        name: CodPostal

    NIA:
      type: string
      maxLength: 15
      description: "Identificador únic a la base de dades de padró del titular de la sol·licitud."
      xml:
        name: NIA


    Desde:
     type: string
     maxLength: 10
     format: date-time
     description: "Data de naixement del titular de la sol·licitud. Format:yyyy-MM-dd"
     xml:
       name: Desde

    MotivoInscripcion:
      type: object
      required:
        - descripcion
      properties:
        codigoVariacion:
          type: string
          maxLength: 1
          description: "Codi causa d'inscripció al domicili. (A: Alta, M: Modificacion) Si no és cap d'aquestes, no s'informa aquest valor."
          enum:
            - A
            - M
          xml:
            name: CodigoVariacion
        causaVariacion:
          type: string
          maxLength: 2
          description: "Codi variació inscripció al domicili."
          xml:
            name: CausaVariacion
        descripcion:
          type: string
          maxLength: 80
          description: "Nom del nucli del domicili."
          xml:
            name: Descripcion
      xml:
        name: MotivoInscripcion
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
tags:
- name: SCDCPAJUv3
  description: '### Consultes al padró històric'
  externalDocs:
    description: 'Manual del cedent'
    url: https://github.com/Fundacio-Bit/emiservbackoffice/blob/main/doc/interoperabilitat/SCDCHPAJUv3/cedent/ManualCedentPadroConvivencia.odt
externalDocs:
  description: "Documents d'interoperabilitat"
  url: http://interoperabilitat.caib.es
