/*
 * SCDHPAJUv3
 * # This is a SCDHPAJUv3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SCDHPAJUv3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.ClaveHojaPadronal;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.Direccion;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.EntColectiva;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.EntSingular;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.MotivoBaja;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.MotivoInscripcion;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.MunicipioRespuesta;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.Nucleo;
import es.caib.scsp.api.cedent.client.SCDHPAJUv3.model.ProvinciaRespuesta;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Domicilio
 */


public class Domicilio {
  @JsonProperty("claveHojaPadronal")
  private ClaveHojaPadronal claveHojaPadronal = null;

  @JsonProperty("provinciaRespuesta")
  private ProvinciaRespuesta provinciaRespuesta = null;

  @JsonProperty("municipioRespuesta")
  private MunicipioRespuesta municipioRespuesta = null;

  @JsonProperty("entColectiva")
  private EntColectiva entColectiva = null;

  @JsonProperty("entSingular")
  private EntSingular entSingular = null;

  @JsonProperty("nucleo")
  private Nucleo nucleo = null;

  @JsonProperty("codUnidadPoblacional")
  private String codUnidadPoblacional = null;

  @JsonProperty("direccion")
  private Direccion direccion = null;

  @JsonProperty("desde")
  private String desde = null;

  @JsonProperty("motivoInscripcion")
  private MotivoInscripcion motivoInscripcion = null;

  @JsonProperty("hasta")
  private String hasta = null;

  @JsonProperty("motivoBaja")
  private MotivoBaja motivoBaja = null;

  public Domicilio claveHojaPadronal(ClaveHojaPadronal claveHojaPadronal) {
    this.claveHojaPadronal = claveHojaPadronal;
    return this;
  }

   /**
   * Get claveHojaPadronal
   * @return claveHojaPadronal
  **/
  @Schema(required = true, description = "")
  public ClaveHojaPadronal getClaveHojaPadronal() {
    return claveHojaPadronal;
  }

  public void setClaveHojaPadronal(ClaveHojaPadronal claveHojaPadronal) {
    this.claveHojaPadronal = claveHojaPadronal;
  }

  public Domicilio provinciaRespuesta(ProvinciaRespuesta provinciaRespuesta) {
    this.provinciaRespuesta = provinciaRespuesta;
    return this;
  }

   /**
   * Get provinciaRespuesta
   * @return provinciaRespuesta
  **/
  @Schema(description = "")
  public ProvinciaRespuesta getProvinciaRespuesta() {
    return provinciaRespuesta;
  }

  public void setProvinciaRespuesta(ProvinciaRespuesta provinciaRespuesta) {
    this.provinciaRespuesta = provinciaRespuesta;
  }

  public Domicilio municipioRespuesta(MunicipioRespuesta municipioRespuesta) {
    this.municipioRespuesta = municipioRespuesta;
    return this;
  }

   /**
   * Get municipioRespuesta
   * @return municipioRespuesta
  **/
  @Schema(description = "")
  public MunicipioRespuesta getMunicipioRespuesta() {
    return municipioRespuesta;
  }

  public void setMunicipioRespuesta(MunicipioRespuesta municipioRespuesta) {
    this.municipioRespuesta = municipioRespuesta;
  }

  public Domicilio entColectiva(EntColectiva entColectiva) {
    this.entColectiva = entColectiva;
    return this;
  }

   /**
   * Get entColectiva
   * @return entColectiva
  **/
  @Schema(description = "")
  public EntColectiva getEntColectiva() {
    return entColectiva;
  }

  public void setEntColectiva(EntColectiva entColectiva) {
    this.entColectiva = entColectiva;
  }

  public Domicilio entSingular(EntSingular entSingular) {
    this.entSingular = entSingular;
    return this;
  }

   /**
   * Get entSingular
   * @return entSingular
  **/
  @Schema(description = "")
  public EntSingular getEntSingular() {
    return entSingular;
  }

  public void setEntSingular(EntSingular entSingular) {
    this.entSingular = entSingular;
  }

  public Domicilio nucleo(Nucleo nucleo) {
    this.nucleo = nucleo;
    return this;
  }

   /**
   * Get nucleo
   * @return nucleo
  **/
  @Schema(description = "")
  public Nucleo getNucleo() {
    return nucleo;
  }

  public void setNucleo(Nucleo nucleo) {
    this.nucleo = nucleo;
  }

  public Domicilio codUnidadPoblacional(String codUnidadPoblacional) {
    this.codUnidadPoblacional = codUnidadPoblacional;
    return this;
  }

   /**
   * Get codUnidadPoblacional
   * @return codUnidadPoblacional
  **/
  @Schema(description = "")
  public String getCodUnidadPoblacional() {
    return codUnidadPoblacional;
  }

  public void setCodUnidadPoblacional(String codUnidadPoblacional) {
    this.codUnidadPoblacional = codUnidadPoblacional;
  }

  public Domicilio direccion(Direccion direccion) {
    this.direccion = direccion;
    return this;
  }

   /**
   * Get direccion
   * @return direccion
  **/
  @Schema(required = true, description = "")
  public Direccion getDireccion() {
    return direccion;
  }

  public void setDireccion(Direccion direccion) {
    this.direccion = direccion;
  }

  public Domicilio desde(String desde) {
    this.desde = desde;
    return this;
  }

   /**
   * Get desde
   * @return desde
  **/
  @Schema(required = true, description = "")
  public String getDesde() {
    return desde;
  }

  public void setDesde(String desde) {
    this.desde = desde;
  }

  public Domicilio motivoInscripcion(MotivoInscripcion motivoInscripcion) {
    this.motivoInscripcion = motivoInscripcion;
    return this;
  }

   /**
   * Get motivoInscripcion
   * @return motivoInscripcion
  **/
  @Schema(description = "")
  public MotivoInscripcion getMotivoInscripcion() {
    return motivoInscripcion;
  }

  public void setMotivoInscripcion(MotivoInscripcion motivoInscripcion) {
    this.motivoInscripcion = motivoInscripcion;
  }

  public Domicilio hasta(String hasta) {
    this.hasta = hasta;
    return this;
  }

   /**
   * Get hasta
   * @return hasta
  **/
  @Schema(description = "")
  public String getHasta() {
    return hasta;
  }

  public void setHasta(String hasta) {
    this.hasta = hasta;
  }

  public Domicilio motivoBaja(MotivoBaja motivoBaja) {
    this.motivoBaja = motivoBaja;
    return this;
  }

   /**
   * Get motivoBaja
   * @return motivoBaja
  **/
  @Schema(description = "")
  public MotivoBaja getMotivoBaja() {
    return motivoBaja;
  }

  public void setMotivoBaja(MotivoBaja motivoBaja) {
    this.motivoBaja = motivoBaja;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Domicilio domicilio = (Domicilio) o;
    return Objects.equals(this.claveHojaPadronal, domicilio.claveHojaPadronal) &&
        Objects.equals(this.provinciaRespuesta, domicilio.provinciaRespuesta) &&
        Objects.equals(this.municipioRespuesta, domicilio.municipioRespuesta) &&
        Objects.equals(this.entColectiva, domicilio.entColectiva) &&
        Objects.equals(this.entSingular, domicilio.entSingular) &&
        Objects.equals(this.nucleo, domicilio.nucleo) &&
        Objects.equals(this.codUnidadPoblacional, domicilio.codUnidadPoblacional) &&
        Objects.equals(this.direccion, domicilio.direccion) &&
        Objects.equals(this.desde, domicilio.desde) &&
        Objects.equals(this.motivoInscripcion, domicilio.motivoInscripcion) &&
        Objects.equals(this.hasta, domicilio.hasta) &&
        Objects.equals(this.motivoBaja, domicilio.motivoBaja);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claveHojaPadronal, provinciaRespuesta, municipioRespuesta, entColectiva, entSingular, nucleo, codUnidadPoblacional, direccion, desde, motivoInscripcion, hasta, motivoBaja);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Domicilio {\n");
    
    sb.append("    claveHojaPadronal: ").append(toIndentedString(claveHojaPadronal)).append("\n");
    sb.append("    provinciaRespuesta: ").append(toIndentedString(provinciaRespuesta)).append("\n");
    sb.append("    municipioRespuesta: ").append(toIndentedString(municipioRespuesta)).append("\n");
    sb.append("    entColectiva: ").append(toIndentedString(entColectiva)).append("\n");
    sb.append("    entSingular: ").append(toIndentedString(entSingular)).append("\n");
    sb.append("    nucleo: ").append(toIndentedString(nucleo)).append("\n");
    sb.append("    codUnidadPoblacional: ").append(toIndentedString(codUnidadPoblacional)).append("\n");
    sb.append("    direccion: ").append(toIndentedString(direccion)).append("\n");
    sb.append("    desde: ").append(toIndentedString(desde)).append("\n");
    sb.append("    motivoInscripcion: ").append(toIndentedString(motivoInscripcion)).append("\n");
    sb.append("    hasta: ").append(toIndentedString(hasta)).append("\n");
    sb.append("    motivoBaja: ").append(toIndentedString(motivoBaja)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
