/*
 * SCDHPAJUv3
 * # This is a SCDHPAJUv3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SCDHPAJUv3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * MotivoInscripcion
 */


public class MotivoInscripcion {
  /**
   * Codi causa d&#x27;inscripció al domicili. (A: Alta, M: Modificacion) Si no és cap d&#x27;aquestes, no s&#x27;informa aquest valor.
   */
  public enum CodigoVariacionEnum {
    A("A"),
    M("M");

    private String value;

    CodigoVariacionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CodigoVariacionEnum fromValue(String text) {
      for (CodigoVariacionEnum b : CodigoVariacionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("codigoVariacion")
  private CodigoVariacionEnum codigoVariacion = null;

  @JsonProperty("causaVariacion")
  private String causaVariacion = null;

  @JsonProperty("descripcion")
  private String descripcion = null;

  public MotivoInscripcion codigoVariacion(CodigoVariacionEnum codigoVariacion) {
    this.codigoVariacion = codigoVariacion;
    return this;
  }

   /**
   * Codi causa d&#x27;inscripció al domicili. (A: Alta, M: Modificacion) Si no és cap d&#x27;aquestes, no s&#x27;informa aquest valor.
   * @return codigoVariacion
  **/
  @Schema(description = "Codi causa d'inscripció al domicili. (A: Alta, M: Modificacion) Si no és cap d'aquestes, no s'informa aquest valor.")
  public CodigoVariacionEnum getCodigoVariacion() {
    return codigoVariacion;
  }

  public void setCodigoVariacion(CodigoVariacionEnum codigoVariacion) {
    this.codigoVariacion = codigoVariacion;
  }

  public MotivoInscripcion causaVariacion(String causaVariacion) {
    this.causaVariacion = causaVariacion;
    return this;
  }

   /**
   * Codi variació inscripció al domicili.
   * @return causaVariacion
  **/
  @Schema(description = "Codi variació inscripció al domicili.")
  public String getCausaVariacion() {
    return causaVariacion;
  }

  public void setCausaVariacion(String causaVariacion) {
    this.causaVariacion = causaVariacion;
  }

  public MotivoInscripcion descripcion(String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

   /**
   * Nom del nucli del domicili.
   * @return descripcion
  **/
  @Schema(required = true, description = "Nom del nucli del domicili.")
  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MotivoInscripcion motivoInscripcion = (MotivoInscripcion) o;
    return Objects.equals(this.codigoVariacion, motivoInscripcion.codigoVariacion) &&
        Objects.equals(this.causaVariacion, motivoInscripcion.causaVariacion) &&
        Objects.equals(this.descripcion, motivoInscripcion.descripcion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigoVariacion, causaVariacion, descripcion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MotivoInscripcion {\n");
    
    sb.append("    codigoVariacion: ").append(toIndentedString(codigoVariacion)).append("\n");
    sb.append("    causaVariacion: ").append(toIndentedString(causaVariacion)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
