/*
 * SCDCPAJUv3
 * # This is a SCDCPAJUv3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SCDCPAJUv3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ClaveHojaPadronal
 */


public class ClaveHojaPadronal {
  @JsonProperty("distrito")
  private String distrito = null;

  @JsonProperty("seccion")
  private String seccion = null;

  @JsonProperty("hoja")
  private String hoja = null;

  public ClaveHojaPadronal distrito(String distrito) {
    this.distrito = distrito;
    return this;
  }

   /**
   * Dada districte del domicili al padró municipal.
   * @return distrito
  **/
  @Schema(required = true, description = "Dada districte del domicili al padró municipal.")
  public String getDistrito() {
    return distrito;
  }

  public void setDistrito(String distrito) {
    this.distrito = distrito;
  }

  public ClaveHojaPadronal seccion(String seccion) {
    this.seccion = seccion;
    return this;
  }

   /**
   * Dada secció del domicili al padró municipal.
   * @return seccion
  **/
  @Schema(required = true, description = "Dada secció del domicili al padró municipal.")
  public String getSeccion() {
    return seccion;
  }

  public void setSeccion(String seccion) {
    this.seccion = seccion;
  }

  public ClaveHojaPadronal hoja(String hoja) {
    this.hoja = hoja;
    return this;
  }

   /**
   * Dada fulla d&#x27;inscripció del domicili al padró municipal.
   * @return hoja
  **/
  @Schema(required = true, description = "Dada fulla d'inscripció del domicili al padró municipal.")
  public String getHoja() {
    return hoja;
  }

  public void setHoja(String hoja) {
    this.hoja = hoja;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClaveHojaPadronal claveHojaPadronal = (ClaveHojaPadronal) o;
    return Objects.equals(this.distrito, claveHojaPadronal.distrito) &&
        Objects.equals(this.seccion, claveHojaPadronal.seccion) &&
        Objects.equals(this.hoja, claveHojaPadronal.hoja);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distrito, seccion, hoja);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClaveHojaPadronal {\n");
    
    sb.append("    distrito: ").append(toIndentedString(distrito)).append("\n");
    sb.append("    seccion: ").append(toIndentedString(seccion)).append("\n");
    sb.append("    hoja: ").append(toIndentedString(hoja)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
