/*
 * SCDCPAJUv3
 * # This is a SCDCPAJUv3 server spec You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pinbal@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.scsp.api.cedent.client.SCDCPAJUv3.api;

import es.caib.scsp.api.cedent.client.SCDCPAJUv3.services.ApiException;
import es.caib.scsp.api.cedent.client.SCDCPAJUv3.model.ModelApiResponse;
import es.caib.scsp.api.cedent.client.SCDCPAJUv3.model.Resultado;
import es.caib.scsp.api.cedent.client.SCDCPAJUv3.model.Solicitud;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScdcpajUv3Api
 */
@Ignore
public class ScdcpajUv3ApiTest {

    private final ScdcpajUv3Api api = new ScdcpajUv3Api();

    /**
     * Realitza una consulta al cedent
     *
     * Realitza una consulta al cedent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void peticionSincronaTest() throws ApiException {
        
        api.getApiClient().setBasePath("http://pinbalcedent:8580/pinbal-services/rest");
        api.getApiClient().setUsername("pinbal");
        api.getApiClient().setPassword("!puW6PHUQC%c");
        
        
        
        Solicitud body = null;
        Resultado response = api.peticionSincrona(body);

        // TODO: test validations
    }
}
